################################################################################
# Description: Makefile for a set of bytecode instructions                     #
#                                                                              #
# Authors: Jean-Raphael Matte                                                  #
# Version: 1.0                                                                 #
################################################################################

# Name of the project
# (use a single word, ex: "myproject")
PROJECTNAME=instructions

# Source file
# Use the .txt suffix for text files
# ex: 'dance.txt' or '$(wildcard *.txt)'
PRJSRC=$(wildcard *.txt)

include ../common.mk
